Fix bug that legacy test case does not work when using 'metadata'
restraint-harness/restraint pull request #300
Opened 2023-07-14 08:49 UTC by tcler

Restraint works in non-rhts_compat mode after added metadata file in legacy test case, that implies that all ENV variable names changed. but legacy test code still use old ENV names.

With this patch to ensure that the original test cases can work regardless of whether it is in compat mode or not.

2023-07-17 11:06 UTC, cbouchar requested changes
The solution is not to change restraint since other have successfully changed their code by following:   https://restraint.readthedocs.io/en/latest/remove_rhts.html   Please close this changeset.

2023-07-17 11:41 UTC, tcler commented
> The solution is not to change restraint since other have successfully changed their code by following: https://restraint.readthedocs.io/en/latest/remove_rhts.html Please close this changeset.

I don't think we should change all legacy test cases just because restraint change the default ENV var name.

2023-07-17 11:57 UTC, cbouchar commented
> > The solution is not to change restraint since other have successfully changed their code by following: https://restraint.readthedocs.io/en/latest/remove_rhts.html Please close this changeset.
> 
> I don't think we should change all legacy test cases just because restraint change the default ENV var name. My ideal tool change process is something like: sh -> bash vi -> vim docker -> podman They try to provide backward compatibility to ensure that old code can run without modification, instead of forcing all old code to adapt to new tools

You have choices. You can continue using 'rhts' or if you want to go non-rhts you need to following the provided documentation like many others have done.

2023-07-17 12:06 UTC, tcler commented
> > > The solution is not to change restraint since other have successfully changed their code by following: https://restraint.readthedocs.io/en/latest/remove_rhts.html Please close this changeset.
> > 
> > 
> > I don't think we should change all legacy test cases just because restraint change the default ENV var name. My ideal tool change process is something like: sh -> bash vi -> vim docker -> podman They try to provide backward compatibility to ensure that old code can run without modification, instead of forcing all old code to adapt to new tools
> 
> You have choices. You can continue using 'rhts' or if you want to go non-rhts you need to following the provided documentation like many others have done.

we hope using metadata file, but not change code : )    and  it doesn't hurt to support both JOBID and RSTRNT_JOBID, why not provide a little more convenience?  just like  bash support  both  $USER and $LOGNAME

2023-07-17 12:19 UTC, cbouchar commented
> > > > The solution is not to change restraint since other have successfully changed their code by following: https://restraint.readthedocs.io/en/latest/remove_rhts.html Please close this changeset.
> > > 
> > > 
> > > I don't think we should change all legacy test cases just because restraint change the default ENV var name. My ideal tool change process is something like: sh -> bash vi -> vim docker -> podman They try to provide backward compatibility to ensure that old code can run without modification, instead of forcing all old code to adapt to new tools
> > 
> > 
> > You have choices. You can continue using 'rhts' or if you want to go non-rhts you need to following the provided documentation like many others have done.
> 
> we hope using metadata file, but not change code : ) and it doesn't hurt to support both JOBID and RSTRNT_JOBID, why not provide a little more convenience? just like bash support both $USER and $LOGNAME

With my experience with restraint, yes it can hurt providing both variables.  Have you tried simply providing the 'metadata' file?  If so, what's causing you issues?

2023-07-17 12:28 UTC, tcler commented
> > > > > The solution is not to change restraint since other have successfully changed their code by following: https://restraint.readthedocs.io/en/latest/remove_rhts.html Please close this changeset.
> > > > 
> > > > 
> > > > I don't think we should change all legacy test cases just because restraint change the default ENV var name. My ideal tool change process is something like: sh -> bash vi -> vim docker -> podman They try to provide backward compatibility to ensure that old code can run without modification, instead of forcing all old code to adapt to new tools
> > > 
> > > 
> > > You have choices. You can continue using 'rhts' or if you want to go non-rhts you need to following the provided documentation like many others have done.
> > 
> > 
> > we hope using metadata file, but not change code : ) and it doesn't hurt to support both JOBID and RSTRNT_JOBID, why not provide a little more convenience? just like bash support both $USER and $LOGNAME
> 
> With my experience with restraint, yes it can hurt providing both variables. Have you tried simply providing the 'metadata' file? If so, what's causing you issues?

our story is: we added metadata file in one of our test case, and in this test case we use ENV REBOOTCOUNT to control reboot times. then with metadata file restraint switch to new mode  and the REBOOTCOUNT became to emty. finally the test falls into an infinite loop.

Curious what problem that providing both var can cause?

2023-07-17 12:52 UTC, cbouchar commented
> our story is: we added metadata file in one of our test case, and in this test case we use ENV REBOOTCOUNT to control reboot times. then with metadata file restraint switch to new mode and the REBOOTCOUNT became to emty. finally the test falls into an infinite loop.
> 
> Curious what problem that providing both var can cause?

I see how when using metadata_file that you are in rhts_compat mode.  Someone put it there with good reason.  Your changes to undo that will not be accepted.  Please change your code to use RSTRNT_REBOOTCOUNT.

2023-07-17 13:46 UTC, tcler commented
> 

Such a reply is not convincing.

2023-07-17 13:55 UTC, cbouchar commented
> Such a reply is not convincing.



> Such a reply is not convincing.

Your code is a special user case.  Restraint has been filled these cases and we stopped accepting special user cases cause it makes Restraint difficult to support.  Other's have changed according to the direction Restraint has taken.  We will not change that direction for one user.  I recommend you change your code or go back to using testinfo file.

2023-07-17 15:43 UTC, StykMartin commented
I completely agree with @cbouchar on this point. The documentation is clear on how Restraint behaves, how environment variables are introduced and what to expect.

We drew a line at how Restraint works with and without RHTS. Any changes to this part must have strong justification and value to be approved.

2023-07-17 17:13 UTC, cbouchar commented
> I completely agree with @cbouchar on this point. The documentation is clear on how Restraint behaves, how environment variables are introduced and what to expect.
> 
> We drew a line at how Restraint works with and without RHTS. Any changes to this part must have strong justification and value to be approved.

Thanks for chiming in Martin!  This change doesn't fit with existing direction.

2023-07-17 17:36 UTC, closed without merging

2023-07-18 00:58 UTC, tcler commented
> I completely agree with @cbouchar on this point. The documentation is clear on how Restraint behaves, how environment variables are introduced and what to expect.

I'm still curious why  have to change the name of the environment ENV?
  And what's wrong with supporting both JOBID RSTRNT_JOBID?  : )

> 
> We drew a line at how Restraint works with and without RHTS. Any changes to this part must have strong justification and value to be approved.

The principle I have always believed in is: try to be backward compatible to provide maximum convenience for users.
Don't settle.